FORMAT: 1A
HOST: https://future150.herokuapp.com

# Future150

The best source for college basketball recruiting, class rankings and elite player profiles. Discover which high school players are the hottest recruits.

## Contacts Collection [/contacts?q={q}page={page}&pageSize={pageSize}]

Displays Future150 contacts

+ Parameters
    + q (string, optional) - Search string
    + page (int, optional) - Current page number
        + Default: 1
    + pageSize (int, optional) - Page size
        + Default: 10


### List All Contacts [GET]

Returns a list of all Future150 contacts.

+ Response 200 (application/json)

        {
            "count": 2,
            "contacts": [
                {
                    "_id": "bd3f7ff5-c1b4-428a-b9a0-8f5e117c3831",
                    "firstName": "Jason",
                    "lastName": "Pratt",
                    "title": "President/Sr. Analyst",
                    "phoneNumber": "312-953-9130",
                    "emailAddress": "jpratt@future150.com",
                    "twitterHandle": "@F150PREZ",
                    "profileImageUrl": "//future150.com/images/uploads/main/jason_pratt.jpg"
                },
                {
                    "_id": "19eea6cb-27dc-4adb-8281-9b228af9cb81",
                    "firstName": "Andrew",
                    "lastName": "Force",
                    "title": "GM / National Analyst",
                    "phoneNumber": "217-521-7004",
                    "emailAddress": "force@Future150.com",
                    "twitterHandle": "@AForceF150",
                    "profileImageUrl": "//future150.com/images/uploads/main/Andrew-Force-Twitter.jpg"
                }
            ]
        }

## Players Collection [/players]

Displays Future150 players

### List All Players [GET]

Returns a list of all Future150 players.

+ Response 200 (application/json)

        {
            "count": "2",
            "players": [
                {
                    "slug": "harry-giles-pf-2016",
                    "firstName": "Harry",
                    "lastName": "Giles"
                },
                {
                    "slug": "joshua-jackson-sg-2016",
                    "firstName": "Josh",
                    "lastName": "Jackson"
                }
            ]
        }

## Player Detail [/players/{slug}]

Displays Future150 player detail

+ Parameters
    + slug (string) - slug of the player

### List Player Detail [GET]

Returns the details of a Future150 player.

+ Response 200 (application/json)

        {
            "slug": "harry-giles-pf-2016",
            "title": "Harry Giles, PF - Winston-Salem, NC (2016)",
            "description": "The most complete information about Winston-Salem, NC's basketball player, Harry Giles, Power Forward (2016) - including bio, recruiting, news and videos.",
            "firstName": "Harry",
            "lastName": "Giles",
            "position": "PF",
            "imageUrl": "//future150.com/images/uploads/profilesbb/2016/Harry-Giles-2016.png",
            "hometownCity": "Winston-Salem",
            "hometownState": "NC",
            "class": "2016"
        }

## Articles Collection [/articles]

Displays Future150 articles

### List All Articles [GET]

Returns a list of all Future150 articles.

+ Response 200 (application/json)

        {
            "count": "4",
            "articles": [
                {
                    "slug": "looking-at-the-1-recruiting-class-kentucky-wildcats",
                    "description": "After picking up a commitment from elite SG Malik Monk, UK vaulted over Duke to take over the #1 spot.",
                    "date": "",
                    "title": "Looking At The #1 Recruiting Class: Kentucky Wildcats",
                    "imageUrl": "//future150.com/images/made/images/uploads/articles/wenyen-gabriel-kentucky-commit_643_341shar-60-.5-10_s_c1_c_c.png"
                },
                {
                    "slug": "johnny-newman-talks-recruitment-goals-for-this-season",
                    "description": "2018 wing John Newman is becoming a big piece for Greensboro Day, and is gaining interest.",
                    "date": "",
                    "title": "Johnny Newman Talks Recruitment And Goals",
                    "imageUrl": "//future150.com/images/made/images/uploads/articles/Johnny_Newman_643_341_90shar-60-.5-10_s_c1_c_c.JPG"
                },
                {
                    "slug": "early-signing-period-comes-to-end-with-a-bang",
                    "description": "The early signing period came to a close in style on Wednesday, as a trio of top-40 recruits all announced their college destinations.",
                    "date": "",
                    "title": "Early Signing Period Comes to End With A Bang",
                    "imageUrl": "//future150.com/images/made/images/uploads/articles/Skal-Labissiere-Malik-Monk_643_341shar-60-.5-10_s_c1_c_t.png"
                },
                {
                    "slug": "tripp-greene-showing-promise",
                    "description": "2018 G Tripp Greene has been showing promise as a potential lead guard at the D1 level",
                    "date": "",
                    "title": "Tripp Greene Showing Promise",
                    "imageUrl": "//future150.com/images/made/images/uploads/articles/IMG_1054_643_341_90shar-60-.5-10_s_c1_c_c.JPG"
                }
            ]
        }

## Article Detail [/articles/{slug}]

Displays Future150 article detail

+ Parameters
    + slug (string) - slug of the article

### List Article Detail [GET]

Returns details of a Future150 article.

+ Response 200 (application/json)

        {
            "slug": "looking-at-the-1-recruiting-class-kentucky-wildcats",
            "title": "Looking At The #1 Recruiting Class: Kentucky Wildcats",
            "description": "After picking up a commitment from elite SG Malik Monk, UK vaulted over Duke to take over the #1 spot.",
            "date": "",
            "title": "Looking At The #1 Recruiting Class: Kentucky Wildcats",
            "imageUrl": "//future150.com/images/made/images/uploads/articles/wenyen-gabriel-kentucky-commit_643_341shar-60-.5-10_s_c1_c_c.png"
        }

## Rankings Collection [/rankings]

Displays Future150 rankings

### List All Rankings for a given year [GET]

Returns a list of all Future150 rankings for a given year.

+ Response 200 (application/json)

        {
            "count": "4",
            "players": [
                {
                    "slug": "harry-giles-pf-2016",
                    "rank": 1,
                    "firstName": "Harry",
                    "lastName": "Giles",
                    "position": "PF",
                    "imageUrl": "//future150.com/images/uploads/profilesbb/2016/Harry-Giles-2016.png"
                },
                {
                    "slug": "joshua-jackson-sg-2016",
                    "rank": 2,
                    "firstName": "Josh",
                    "lastName": "Jackson",
                    "position": "SG",
                    "imageUrl": "//future150.com/images/uploads/profilesbb/2016/Josh-Jackson-2016.png"
                },
                {
                    "slug": "jayson-tatum-sf-2016",
                    "rank": 3,
                    "firstName": "Jayson",
                    "lastName": "Tatum",
                    "position": "SF",
                    "imageUrl": "//future150.com/images/uploads/profilesbb/i_(4).png"
                },
                {
                    "slug": "thon-maker-c-2016",
                    "rank": 4,
                    "firstName": "Thon",
                    "lastName": "Maker",
                    "position": "C",
                    "imageUrl": "//future150.com/images/uploads/profilesbb/i_(2).png"
                }
            ]
        }

## Events Collection [/events]

Displays Future150 events

### List All Events [GET]

Returns a list of all Future150 events.

+ Response 200 (application/json)

        {
            "count": "2",
            "events": [
                {
                    "slug": "underclassmen-spring-breakout",
                    "title": "Underclassmen Spring Breakout",
                    "city": "Homewood",
                    "state": "AL",
                    "imageUrl": "//future150.com/images/made/images/uploads/event-headers/Spring-Breakout-Tournament-1_634_336shar-40_s.jpg"
                },
                {
                    "slug": "easter-showcase-houston",
                    "title": "Easter Showcase Houston",
                    "city": "Houston",
                    "state": "TX",
                    "imageUrl": "//future150.com/images/made/images/uploads/event-headers/Easter-Showcase-Houston_634_336shar-40_s.jpg"
                },
                {
                    "slug": "main-event-houston",
                    "title": "Main Event Houston",
                    "city": "Humble",
                    "state": "TX",
                    "imageUrl": "//future150.com/images/made/images/uploads/event-headers/Main-Event-Houston-2016_634_336shar-40_s.jpg"
                }
            ]
        }

## Videos Collection [/videos]

Displays Future150 videos

### List All Videos [GET]

Returns a list of all Future150 videos.

+ Response 200 (application/json)

        {
            "count": "3",
            "videos": [
                {
                    "title": "Jacob Collins 6'1'' SG 2017 Future150 All American",
                    "youTubeId": "-pSIr7aOuFc"
                },
                {
                    "title": "Hunter Falconer 6'0'' PG 2017 Future150 All American",
                    "youTubeId": "l2EP7Uw7v_s"
                },
                {
                    "title": "Jonte Williams 6'8'' 2017 FUTURE150 All American",
                    "youTubeId": "FCDvU5VmlBQ"
                }
            ]
        }